### ISSUE TITLE
[BUG] Creating project folder failed!

### ISSUE THREAD

**Issue by sumwun1** [Ravbug/UnityHubNative#4] opened 2021-11-26 20:13 UTC
**Describe the bug**
Every time I try to create a new project, I get a pop-up window that says "Creating project folder failed!" and no other error messages or logs. The hub also successfully creates the project folder, but it's empty. I made sure to choose a location that doesn't already contain a folder with the same name as the project. 

**To Reproduce**
1. add "C:\Program Files\Unity\Hub\Editor\2021.1.25f1\Editor" to install search paths
2. click "Projects" -> "Create New"
3. name the project 
4. set location to a folder than doesn't already contain a sub-folder with the same name as the project
5. select "3d-5.0.4.tgz"
6. click "Create"

**Expected behavior**
I expected the hub to put files in the project folder and not say something failed. 

**Computer information:**
- OS: Windows 10 Home version 20H2 OS build 19042.1348
- IDE version (if applicable): Visual Studio 2019

**Comment by Ravbug** [comment] 2021-11-27 06:59
I'm not able to reproduce this, perhaps it could be a permissions issue? https://answers.unity.com/questions/1637674/creating-project-folder-failedcreating-project-fol.html

"Creating project folder failed" is not my dialog unfortunately. Does the official hub allow creating a project in that location?

**Comment by sumwun1** [comment] 2021-11-28 16:06
Yes, the official hub works just fine when I try to create a project with the same name, location, and template.

**Comment by Ravbug** [comment] 2022-03-18 16:37
I haven't been able to repro this on the latest version so I'm closing this issue.

**Closed by Ravbug** 2022-03-18 16:37 UTC
Labels: bug, can't reproduce
